name: CI - Test build

on:
  push:
    branches:
      - '!master'
  workflow_dispatch:

jobs:
  build:
    name: "Test docker build"
    if: ${{ github.repository == 'stephane-klein/restic-pg_dump-docker' && contains(github.ref, 'refs/heads/master') }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/i386
          push: false
          tags: stephaneklein/restic-pg_dump
          file: Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
